// test download youtube video to mp3

### POST REQUEST

GET  http://localhost:8000/api/downloadYoutubeVideo
Content-Type: application/json

{
   "url": "https://www.youtube.com/watch?v=41ocqQXRRLI",
  
}
